kind: pipeline
name: default

services:
  - name: vault
    image: vault:1.7.1
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: dev
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
  - name: etcd
    image: bitnami/etcd:3
    environment:
      ALLOW_NONE_AUTHENTICATION: yes

environment:
  VAULT_DEV_LISTEN_ADDRESS: http://vault:8200
  VAULT_DEV_ROOT_TOKEN_ID: dev
  FDEVS_CONFIG_ETCD_HOST: etcd:2379

steps:
- name: test 
  image: golang
  commands:
  - go test -parallel 10 -race ./... 

- name: golangci-lint
  image: golangci/golangci-lint:v1.53
  commands:
  - golangci-lint run
