kind: pipeline
name: default

environment:
  VAULT_DEV_LISTEN_ADDRESS: http://vault:8200
  VAULT_DEV_ROOT_TOKEN_ID: dev
  FDEVS_CONFIG_ETCD_HOST: etcd:2379

steps:
- name: test 
  image: golang
  commands:
  # - go test -parallel 10 -race ./... 
  # - go test -race ./... 
  - go test ./... 

- name: golangci-lint
  image: golangci/golangci-lint:v1.55
  commands:
  - golangci-lint run
