---
kind: pipeline
name: default

environment:
  VAULT_DEV_LISTEN_ADDRESS: http://vault:8200
  VAULT_DEV_ROOT_TOKEN_ID: dev
  FDEVS_CONFIG_ETCD_HOST: etcd:2379

steps:
- name: test 
  image: golang
  commands:
  # - go test -parallel 10 -race ./... 
  - go test ./... 

- name: golangci-lint
  image: golangci/golangci-lint:v1.55
  commands:
  - golangci-lint run

---
kind: pipeline
name: json

steps:
- name: test 
  image: golang
  commands:
  - cd provider/json
  - go test ./... 

- name: golangci-lint
  image: golangci/golangci-lint:v1.55
  commands:
  - cd provider/json
  - golangci-lint run

---
kind: pipeline
name: yaml

steps:
- name: test 
  image: golang
  commands:
  - cd provider/yaml
  - go test ./... 

- name: golangci-lint
  image: golangci/golangci-lint:v1.55
  commands:
  - cd provider/yaml
  - golangci-lint run

---
kind: pipeline
type: docker
name: ini

steps:
- name: test 
  image: golang
  failure: ignore # runtime/cgo: pthread_create failed: Operation not permitted
  commands:
  - cd provider/ini
  - go test ./... 

- name: golangci-lint
  image: golangci/golangci-lint:v1.55
  commands:
  - cd provider/ini
  - golangci-lint run

