---
kind: pipeline
name: default

steps:
- name: test 
  image: golang
  commands:
  # - go test -parallel 10 -race ./... 
  - go test ./... 

- name: golangci-lint
  image: golangci/golangci-lint:v1.55
  commands:
  - golangci-lint run

---
kind: pipeline
name: json

steps:
- name: test 
  image: golang
  commands:
  - cd provider/json
  - go test ./... 

- name: golangci-lint
  image: golangci/golangci-lint:v1.55
  commands:
  - cd provider/json
  - golangci-lint run

---
kind: pipeline
name: yaml

steps:
- name: test 
  image: golang
  commands:
  - cd provider/yaml
  - go test ./... 

- name: golangci-lint
  image: golangci/golangci-lint:v1.55
  commands:
  - cd provider/yaml
  - golangci-lint run

---
kind: pipeline
type: docker
name: ini

steps:
- name: test 
  image: golang
  failure: ignore # runtime/cgo: pthread_create failed: Operation not permitted
  commands:
  - cd provider/ini
  - go test ./... 

- name: golangci-lint
  image: golangci/golangci-lint:v1.55
  commands:
  - cd provider/ini
  - golangci-lint run


---
kind: pipeline
type: docker
name: toml

steps:
- name: test 
  image: golang
  commands:
  - cd provider/toml
  - go test ./... 

- name: golangci-lint
  image: golangci/golangci-lint:v1.55
  commands:
  - cd provider/toml
  - golangci-lint run


---
kind: pipeline
type: docker
name: etcd

environment:
  FDEVS_CONFIG_ETCD_HOST: etcd:2379

services:
  - name: etcd
    image: bitnami/etcd:3.5.11
    environment:
      ALLOW_NONE_AUTHENTICATION: yes

steps:
- name: test 
  image: golang
  failure: ignore # runtime/cgo: pthread_create failed: Operation not permitted
  commands:
  - cd provider/etcd
  - go test ./... 

- name: golangci-lint
  image: golangci/golangci-lint:v1.55
  commands:
  - cd provider/etcd
  - golangci-lint run

---
kind: pipeline
type: docker
name: vault

environment:
  VAULT_DEV_LISTEN_ADDRESS: http://vault:8200
  VAULT_DEV_ROOT_TOKEN_ID: dev

services:
  - name: vault
    image: vault:1.13.3
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: dev
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200

steps:
- name: test 
  image: golang
  failure: ignore # runtime/cgo: pthread_create failed: Operation not permitted
  commands:
  - cd provider/vault
  - go test ./... 

- name: golangci-lint
  image: golangci/golangci-lint:v1.55
  commands:
  - cd provider/vault
  - golangci-lint run

---
kind: pipeline
type: docker
name: definition

steps:
- name: test 
  image: golang
  commands:
  - cd provider/definition
  - go test ./... 

- name: golangci-lint
  image: golangci/golangci-lint:v1.55
  commands:
  - cd provider/definition
  - golangci-lint run

