run:
  timeout: 5m

linters-settings:
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 2
    gocyclo:
      min-complexity: 15
    golint:
      min-confidence: 0
    govet:
      check-shadowing: true
    lll:
      line-length: 140
    maligned:
      suggest-new: true
    misspell:
      locale: US  
    varnamelen:
      min-name-length: 2

linters:
    enable-all: true
    disable:
      - exhaustivestruct
      - maligned
      - interfacer
      - scopelint
      - exhaustruct
      - depguard
      - nolintlint
      #deprecated
      - structcheck
      - varcheck
      - golint
      - deadcode
      - ifshort
      - nosnakecase

      - ireturn # implement provider interface

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - exhaustivestruct
        - wrapcheck
        - exhaustruct
        - varnamelen
        - tenv
        - funlen
    - path: test/*
      linters:
        - gomnd
        - exhaustivestruct
        - wrapcheck
        - exhaustruct
        - varnamelen
